{
 "title": "Clientservice",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Quantile 0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,uri,method,status,exception) (rate(client_controller_requests_seconds_bucket{}[2m])))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri,method,status,exception) (rate(client_controller_requests_seconds_count{}[2m]))"
    }
   ]
  },
  {
   "title": "Quantile 0.95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le,uri,method,status,exception) (rate(client_controller_requests_seconds_bucket{}[2m])))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri,method,status,exception) (rate(client_controller_requests_seconds_count{status!=\"200\"}[2m]))"
    },
    {
     "expr": "sum by (uri,method,status,exception) (rate(client_controller_requests_seconds_count{exception!=\"None\"}[2m]))"
    }
   ]
  },
  {
   "title": "Quantile 0.5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le,uri,method,status,exception) (rate(client_controller_requests_seconds_bucket{}[2m])))"
    }
   ]
  }
 ]
}