apiVersion: batch/v1
kind: Job
metadata:
  name: stresstest
spec:
  template:
    metadata:
      name: stresstest
    spec:
      containers:
      - name: stresstest-get
        image: jordi/ab
        command: ['sh','-c','while true ; do ab -n5 http://clientservice-clientservice-chart:9000/client ; sleep 1 ; done & while true ; do ab -n5 http://clientservice-clientservice-chart:9000/client/10 ; sleep 1 ; done & while true ; do echo "{\"firstName\":\"FirstName$RANDOM\",\"lastName\":\"LastName$RANDOM\",\"email\":\"name$RANDOM@email$RANDOM.xxx\",\"phone\":\"+x-xxx-$RANDOM\"}" > newClient.json; ab -n5 -p ./newClient.json -T application/json http://clientservice-clientservice-chart:9000/client ; sleep 1 ; done & while true ; do echo "{\"firstName\":\"FirstName$RANDOM\",\"lastName\":\"LastName$RANDOM\",\"email\":\"name$RANDOM@email$RANDOM.xxx\",\"phone\":\"+x-xxx-$RANDOM\"}" > editClient.json; ab -n5 -u ./editClient.json -T application/json http://clientservice-clientservice-chart:9000/client/14 ; sleep 1 ; done & while true ; do ab -n5 -m DELETE http://clientservice-clientservice-chart:9000/client/$((20 + RANDOM % 11000)) ; sleep 1 ; done']
      restartPolicy: Never
