apiVersion: batch/v1
kind: Job
metadata:
  name: client-initdb
spec:
  template:
    metadata:
      name: client-initdb
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        env:
          - name: DATABASE_URI
            value: "postgresql://postgres:postgres@postgres/dbhealth"
        image: postgres:9.6
        command:
          - sh
          - "-c"
          - |
            psql $DATABASE_URI <<'EOF'
              CREATE TABLE public.client (id bigint NOT NULL,email character varying(255),first_name character varying(255),last_name character varying(255),phone character varying(255));
              ALTER TABLE public.client OWNER TO postgres;
              ALTER TABLE public.client_id_seq OWNER TO postgres;
              ALTER TABLE ONLY public.client ADD CONSTRAINT client_pkey PRIMARY KEY (id);
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (1,'Jack', 'Bauer', NULL, NULL);
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (2,'Chloe', 'O''Brian', NULL, NULL);
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (3,'Kim', 'Bauer', NULL, NULL);
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (4,'David', 'Palmer', NULL, NULL);
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (5,'Michelle', 'Dessler', NULL, NULL);
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (6,'Evgeniy', 'Popoff', 'egeny-popov@mail.ru', '+7-999-7654321');
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (7,'Jack', 'Bauer', 'jackbauer@outlook.com', '+2-2308420948');
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (8,'Kim', 'Bauer', 'kimbauer@mail.ru', '+5-20842040800');
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (9,'Josh', 'Long', 'joshlong@rambler.ru', '+3-230842034');
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (10,'Jeff', 'Dean', 'jeffdean@gmail.com', '+8-93875493847');
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (11,'David', 'Palmer', 'davidpalmer@i-teco.ru', '+4-23984203423');
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (12,'Michelle', 'Dessler', 'michelledessler@microsoft.com', '+0-198232398');
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (13,'Chloe', 'O''Brian', 'chloeobrian@live.com', '+7-48203482034');
              INSERT INTO public.client (id,first_name,last_name,email,phone) VALUES (14,'John', 'Woo', 'johnwoo@yahoo.com', '+1-43234234');
              CREATE SEQUENCE public.client_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
              SELECT pg_catalog.setval('public.client_id_seq', 15, false);
            EOF
  backoffLimit: 2
