apiVersion: batch/v1
kind: Job
metadata:
  name: client-initdb
spec:
  template:
    metadata:
      name: client-initdb
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        env:
          - name: DATABASE_URI
            value: "postgresql://postgres:postgres@postgres/dbhealth"
        image: postgres:9.6
        command:
          - sh
          - "-c"
          - |
            psql $DATABASE_URI <<'EOF'
              INSERT INTO public.role_table (id,name) VALUES (1,'ROLE_ADMIN');
              INSERT INTO public.role_table (id,name) VALUES (2,'ROLE_USER');
            EOF
  backoffLimit: 2
